### ISSUE TITLE
Downloading the repo and running the examples locally doesn't produce any animation, except for the box animation

### ISSUE THREAD

**Issue by PrashantSaikia** [Bruno-Odinukweze/PyWeb3D#35]
Is there anything we need to do before opening the HTML files, to display the animations as shown in your website? For example, let's take [`webgl_3D_model_animation.html`](https://www.pyweb3d.org/examples/#webgl_3D_model_animation). Here is what I get when I git clone the repo and open the HTML file locally:

<img width="1440" alt="Screenshot 2023-04-01 at 3 01 50 PM" src="https://user-images.githubusercontent.com/39755678/229278151-bf6900e9-1279-4d21-b35e-37e2700dd27a.png">

**Comment by Bruno-Odinukweze** [comment]
Hi Prashant, I could see that the models are not loading on your end, are you getting any error messages on your console?

**Comment by PrashantSaikia** [comment]
Hi Bruno. When I open the `loading_3d_models_NissanZProto.html` file and the `webgl_3D_model_animation.html` file in Chrome, the right click itself doesn't work, so I can't inspect the page and see the console. But the right click does work when opening the `webaudio_play_audio.html` file, and when I click on Play, these are the errors shown in the console:

<img width="1440" alt="Screenshot 2023-04-01 at 4 58 40 PM" src="https://user-images.githubusercontent.com/39755678/229286265-fc567782-a6f8-4d5c-99b0-fcbfff9b49e8.png">

**Comment by Bruno-Odinukweze** [comment]
`from origin 'null' has been blocked by CORS policy` mean that Chrome is blocking the request because they are not from the same origin. It's a security feature in modern browsers. You could read more about Same-origin policy ( [](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy )).
 
 However, to resolve the issue, serve the files using a local server. If you're using VS Code, you could install the live server extension or run the python built-in server
 
```
 //Python 2.x
python -m SimpleHTTPServer

//Python 3.x
python -m http.server
```
checkout other live servers listed in the installation guide [](https://www.pyweb3d.org/docs/docs.html#manual/en/introduction/Installation)

**Comment by Bruno-Odinukweze** [comment]
Hi Prashant, lemme know if the above solution works for you
